name: Deploy to ECR

on:
  workflow_dispatch:
  
jobs:
  docker_build_push_ecr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: myapp
        IMAGE_TAG: ${{ steps.tag_version.outputs.new_version  }}      
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


    - name: Output image digest
      id: output-digest
      run: |
        echo "digest: ${{ steps.build-and-push.outputs.digest }} size:"

    - name: Run Prisma Cloud 
      id: prisma-cloud
      uses: bridgecrewio/checkov-action@master
      env:
       PRISMA_API_URL: https://api4.prismacloud.io
      with:
       api-key: ${{ secrets.BC_API_KEY }}
       use_enforcement_rules: true
       download_external_modules: true
       repo_root_for_plan_enrichment: ./  
